### PR TITLE
Gem implementation

### PR DESCRIPTION
**Pull request by akilmadan**
Please note this PR depends on: https://github.com/sealink/tenants_helper/pull/1

### CODE REVIEW

**Comment by msmirnoff** [comment]
@vgmaster21 
I can't see where this PR modifies any of the boilerplate code so I don't really understand why it is based on top of that PR, the changes are independent.

**Comment by msmirnoff** [comment]
@vgmaster21 
Please review the above comments and let me know what you think.

**Comment by akilmadan** [comment]
@msmirnoff  Agreed about the boilerplate stuff. It's the way I branched off of the boilerplate branch that means that the commits also carry over. Maybe I need to do it a better way.

**Comment by msmirnoff** [comment]
@vgmaster21 
For the boilerplate stuff, it must be the branching. Maybe we can work together on the next one so I can understand what's going on.

**Comment by msmirnoff** [comment]
:+1:

**Comment by akilmadan** [comment]
Sounds like a good idea @msmirnoff

**Comment by alvinypyim** [comment]
:+1: 

Just my personally preference, there are a few optional brackets that we can omit.

**Pull request merged**
